name: breast_cancer_diagnostic
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - shiny
  - shinywidgets
  - jupyter
  - ipykernel
  - anywidget
  - python-dotenv