name: breast_cancer_diagnostic
channels:
  - conda-forge
dependencies:
  - numpy
  - python=3.12
  - plotly
  - shiny
  - jupyter
  - python-dotenv
  - scikit-learn
  - pandas
  - ipykernel
  - matplotlib
  - anywidget
  - seaborn
  - shinywidgets
  - xgboost